-- CreateTable
CREATE TABLE "MortgageApplication" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "employmentStatus" TEXT,
    "annualIncome" DECIMAL(15,2),
    "desiredLoanAmount" DECIMAL(15,2),
    "loanType" TEXT,
    "loanTerm" INTEGER,
    "propertyType" "PropertyType",
    "mortgagePurchaseAmount" DECIMAL(15,2),
    "mortgageDownPayment" DECIMAL(15,2),
    "mortgageInterestRate" DECIMAL(5,3),
    "mortgageLoanTerm" INTEGER,
    "mortgageEstMonthly" DECIMAL(15,2),
    "mortgagePrincipalInterest" DECIMAL(15,2),
    "mortgagePropertyTax" DECIMAL(15,2),
    "mortgageHomeInsurance" DECIMAL(15,2),
    "refinanceLoanAmount" DECIMAL(15,2),
    "refinanceHomeValue" DECIMAL(15,2),
    "refinanceInterestRate" DECIMAL(5,3),
    "refinanceFico" INTEGER,
    "refinanceLoanTerm" INTEGER,
    "refinanceEstMonthly" DECIMAL(15,2),
    "refinancePrincipalInterest" DECIMAL(15,2),
    "refinancePropertyTax" DECIMAL(15,2),
    "refinanceHomeInsurance" DECIMAL(15,2),
    "refinanceHoa" DECIMAL(15,2),
    "message" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MortgageApplication_pkey" PRIMARY KEY ("id")
);
